### ISSUE TITLE
If the calendar has multiple events it creates a new calendar, how to merge into default calendar?

### ISSUE THREAD

**Issue by aviyepuri** [saw303/grails-ic-alender#17]
Hi
The calendar invites are created dynamically, If the calendar has one event it works fine and merges it to default calendar but if the calendar had two events its creating a new calendar.
How to merge it into default calendar?

**Comment by saw303** [comment]
Can you provide an example to reproduce the behaviour you are explaining?

**Comment by aviyepuri** [comment]
def builder = new ICalendarBuilder()
        builder.calendar {
            events {
                for (int i = 0; i < emailModel?.reports?.size; i++) {
                    event(start: emailModel.reports[i].itineraryModel.primaryLeg.etd.time,
                            end: emailModel.reports[i].itineraryModel.primaryLeg.eta.time,
                            description: prepareIcsSummary(emailModel.reports[i]),
                            summary: prepareIcsDescription(emailModel.reports[i]),
                            timezone: 'UTC',
                            uid: emailModel?.reports[i]?.itineraryModel?.reservationId?.toString()) {
                        organizer(email: fromEmailAddress)
                    }
                }
            }
        }
        return builder.cal.toString().getBytes('UTF-8')
    }

**Comment by aviyepuri** [comment]
I'm using Microsoft outlook 2010 as the Calendar.

**Comment by saw303** [comment]
Can you provide the iCal output?

**Comment by aviyepuri** [comment]
![example screen shot](https://cloud.githubusercontent.com/assets/13755617/11784511/b11717e2-a24a-11e5-862c-3b1fac624f00.png)

**Comment by saw303** [comment]
Can you attach the raw `Reservation.ics` file? I suspect an Outlook issue but I would like to import the file myself into my Outlook.

**Comment by aviyepuri** [comment]
https://github.com/saw303/grails-ic-alender/files/61500/Calendar.ics.txt

Unfortunately i'm not able to upload ics files so i extendend with .txt format, so please remove .txt format at the end.
The invites are on June 29th and June 30th of 2015

**Comment by saw303** [comment]
Know I understand. You would like to set these Microsoft specific properties `X-WR-RELCALID` and `X-PRIMARY-CALENDAR` to the `VCALENDAR`.

A final question. What Grails version do you use?

**Comment by aviyepuri** [comment]
app.grails.version=2.4.4

**Comment by aviyepuri** [comment]
the example you provided:
calendar(xproperties: ['X-WR-RELCALID': '1234', 'X-PRIMARY-CALENDAR': 'TRUE']) {
    events {
        allDayEvent(date: new java.util.Date(), summary: 'Text') {
            organizer(name: 'Silvio', email: 'abc@ch.ch')
            reminder(minutesBefore: 5, description: 'Alarm 123')
        }
    }
}

It has only one event, the problem persists when it has two or more events

**Comment by saw303** [comment]
The following example contains two events and due to the `X-PRIMARY-CALENDAR` property it tells Microsoft Outlook to store all the events of the calendar in the primary Outlook calendar.

````
calendar(xproperties: ['X-WR-RELCALID': '1234', 'X-PRIMARY-CALENDAR': 'TRUE']) {
    events {
          event start: new Date() - 2, end: new Date() - 1, description: 'Hi all', summary: 'Short info'
          event start: new Date() + 1, end: new Date() + 2, description: 'Hi all', summary: 'Short info1'
    }
}
````
It creates the following output:
````
BEGIN:VCALENDAR
PRODID:-//Grails iCalendar plugin//NONSGML Grails iCalendar plugin//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-RELCALID:1234
X-PRIMARY-CALENDAR:TRUE
BEGIN:VEVENT
DTSTAMP:20151216T060613Z
DTSTART;TZID=Europe/Zurich:20151214T070600
DTEND;TZID=Europe/Zurich:20151215T070600
SUMMARY:Short info1
UID:20151216T060613Z-iCalPlugin-Grails@fe80:0:0:0:1cc1:a9ff:fe6a:33ba%awdl0
TZID:Europe/Zurich
DESCRIPTION:Hi all
ORGANIZER:
METHOD:PUBLISH
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20151216T060618Z
DTSTART;TZID=Europe/Zurich:20151217T070600
DTEND;TZID=Europe/Zurich:20151218T070600
SUMMARY:Short info1
UID:20151216T060618Z-iCalPlugin-Grails@fe80:0:0:0:1cc1:a9ff:fe6a:33ba%awdl0
TZID:Europe/Zurich
DESCRIPTION:Hi all
ORGANIZER:
METHOD:PUBLISH
END:VEVENT
END:VCALENDAR
````

If I store this output in a file called `demo.ics` and then tell Microsoft Outlook to import it, it creates two events in my main calendar. As you can see the `demo.ics` contains the X-Properties `X-PRIMARY-CALENDAR` and `X-WR-RELCALID` you requested.

Can you provide me a iCalendar output (`.ics` file) the contains the expected output? I am interested in a `.ics` file that has not been exported by Microsoft Outlook and fulfills your expectations.

**Comment by aviyepuri** [comment]
Hi 
I think i need to explain my use case, i have a mail sending client from which it sends pdf and ics as attachment with some body. 
User will not save it to his hard drive and then import it instead the user clicks on it and thats where it creates a shared calendar.
After what you said i actually saved the ics file on my desktop and imported it to my outlook, which worked fine as expected.
But when we click on it directly, even from the desktop instead of importing it. Outlook 2010 creates a new calendar

Here is my ics file
https://github.com/saw303/grails-ic-alender/files/64160/Reservation.ics.txt

**Comment by saw303** [comment]
Thank you for explaining your use case. I understand that you probably send the boarding pass (the pdf attachment) and the flight dates (the ics calendar file) to your customer.

Since the `ics` file seems to be valid it seems that you suffer from a bug in Microsoft Outlook 2010. I have tested it with Outlook 2011 & 2016 for Mac by sending the `ics` file as an email attachment and everything worked out as expected.

There are two options
* Either create separate `ics` files for each event and attach it to the mail
* or try to find the reason why Outlook 2010 behaves that way. If you can send me a valid `ics` file that works for you I can continue investigating.

But for now I don't know how I can support you further on this. I would be very interested in the solution how to solve this problem so maybe you can keep me posted on this.

**Comment by aviyepuri** [comment]
Thank you so much for all your help, I really appreciate it.
I will keep you posted for sure,if i found a solution to this.

**Comment by aviyepuri** [comment]
Hi 
I think there is no solutions for it. So i thought of going with creating seperate ics file for each event.
Is there a way to auto update the event? I tried to import two ics's which has same uid but its importing both. Whats the way to auto update an event?

**Comment by saw303** [comment]
I did some investigation on Google but currently I'm not able to provide you an answer to your latest questions. 

I suggest you ask your question on Stackoverflow or directly to the ical4j community. 

Please keep me posted if you've got updates on this.

**Comment by soumyajit-ghosh** [comment]
Has there been any update by microsoft to resolve this issue?

**Comment by catalinberta** [comment]
I create the events in the calendar app on MacOS, I select them and then: File -> Export -> Export...
Works for me at least

**Comment by Hafzal-mhl** [comment]
Microsoft has not address the gap even in M365 Outlook Version 2103. Outlook still opens the ics file in a new Calendar when multiple events are there same file.
